"use client"

import Image from "next/image"

import SignInForm from "./sign-up-form"

export default function SignUp() {
  // const [imageSrc, setImageSrc] = useState("/placeholder.svg?height=800&width=600")

  

  return (
    <main className="flex h-full bg-background overflow-hidden w-[100%]">
      {/* Left Side - Form */}
      <div className="w-[60%] h-screen relative z-10 bg-[#000000] flex justify-center items-center ">

        <SignInForm />

      </div>

      {/* Right Side - Image */}
      <div className="flex-1 h-screen relative bg-gray-900 w-[40%]">
        <div className="absolute inset-0 rounded-tl-[50px] rounded-bl-[50px] overflow-hidden">
          <Image 
            src="https://firebasestorage.googleapis.com/v0/b/wild-mind-ai.firebasestorage.app/o/vyom_static_landigpage%2Fsignup%2F3.png?alt=media&token=e67afc08-10e0-4710-b251-d9031ef14026" 
            alt="Stylized 3D Character" 
            fill 
            className="object-cover object-center object-[center_25%] scale-100 " 
            priority 
          />
          
          {/* Bottom Black Gradient Overlay */}
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent"></div>
          
          {/* Attribution Text - Bottom Right */}
          <div className="absolute bottom-6 right-6 text-white text-right z-10">
            <p className="text-xs opacity-80">Generated by</p>
            <p className="text-sm font-semibold">Aryan Prajapati</p>
          </div>
        </div>
      </div>
    </main>
  )
}
